# <VirtualHost *:80>
# 	ServerName localhost

# 	ProxyPreserveHost On

# 	RewriteEngine On
# 	RewriteCond %{HTTPS} !=on
# 	RewriteRule ^/(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
# </VirtualHost>

# # Config Https later
# <VirtualHost *:443>
# 	SSLEngine on
# 	SSLCertificateFile /certs/server.cert
# 	SSLCertificateKeyFile /certs/server.key

# 	SSLProxyEngine On
# 	ProxyPreserveHost On

# 	ProxyPass "/" "http://web:5117/"
# 	ProxyPassReverse "/" "http://web:5117/"
# </VirtualHost>

<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass "/" "http://web:5117/"
    ProxyPassReverse "/" "http://web:5117/"
</VirtualHost>